import Navbar from "@/components/Navbar";
import "./globals.css";
import MyProfile from "@/components/MyProfile";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-slate-800">
        <Navbar />
        <MyProfile />
        {children}
      </body>
    </html>
  );
}
